-- Структура полной базы shoestore: только таблицы, связи, ограничения и индексы.
-- Выполнить один раз в НОВОЙ ПУСТОЙ базе shoestore2 (проверено на PostgreSQL 18).
-- Данные, владельцы объектов и история миграций не включены.
BEGIN;

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

CREATE EXTENSION IF NOT EXISTS citext WITH SCHEMA public;

CREATE EXTENSION IF NOT EXISTS pg_trgm WITH SCHEMA public;

SET default_tablespace = '';

SET default_table_access_method = heap;

CREATE TABLE public."AspNetRoleClaims" (
    "Id" integer NOT NULL,
    "RoleId" text NOT NULL,
    "ClaimType" text,
    "ClaimValue" text
);

ALTER TABLE public."AspNetRoleClaims" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."AspNetRoleClaims_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public."AspNetRoles" (
    "Id" text NOT NULL,
    "Name" character varying(256),
    "NormalizedName" character varying(256),
    "ConcurrencyStamp" text
);

CREATE TABLE public."AspNetUserClaims" (
    "Id" integer NOT NULL,
    "UserId" text NOT NULL,
    "ClaimType" text,
    "ClaimValue" text
);

ALTER TABLE public."AspNetUserClaims" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."AspNetUserClaims_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public."AspNetUserLogins" (
    "LoginProvider" text NOT NULL,
    "ProviderKey" text NOT NULL,
    "ProviderDisplayName" text,
    "UserId" text NOT NULL
);

CREATE TABLE public."AspNetUserRoles" (
    "UserId" text NOT NULL,
    "RoleId" text NOT NULL
);

CREATE TABLE public."AspNetUserTokens" (
    "UserId" text NOT NULL,
    "LoginProvider" text NOT NULL,
    "Name" text NOT NULL,
    "Value" text
);

CREATE TABLE public."AspNetUsers" (
    "Id" text NOT NULL,
    "UserName" character varying(256),
    "NormalizedUserName" character varying(256),
    "Email" character varying(256),
    "NormalizedEmail" character varying(256),
    "EmailConfirmed" boolean NOT NULL,
    "PasswordHash" text,
    "SecurityStamp" text,
    "ConcurrencyStamp" text,
    "PhoneNumber" text,
    "PhoneNumberConfirmed" boolean NOT NULL,
    "TwoFactorEnabled" boolean NOT NULL,
    "LockoutEnd" timestamp with time zone,
    "LockoutEnabled" boolean NOT NULL,
    "AccessFailedCount" integer NOT NULL,
    "AvatarUrl" text,
    "DisplayName" character varying(80)
);

CREATE TABLE public."Brands" (
    "Id" integer NOT NULL,
    "Name" public.citext NOT NULL,
    "Description" text
);

ALTER TABLE public."Brands" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Brands_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public."CatalogAuditLogs" (
    "Id" integer NOT NULL,
    "EntityType" character varying(40) NOT NULL,
    "EntityId" integer NOT NULL,
    "Action" character varying(60) NOT NULL,
    "Summary" character varying(300) NOT NULL,
    "ActorUserId" text,
    "CreatedAt" timestamp with time zone NOT NULL
);

ALTER TABLE public."CatalogAuditLogs" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."CatalogAuditLogs_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public."Categories" (
    "Id" integer NOT NULL,
    "Name" public.citext NOT NULL
);

ALTER TABLE public."Categories" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Categories_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public."Favorites" (
    "Id" integer NOT NULL,
    "UserId" character varying(450) NOT NULL,
    "ProductId" integer NOT NULL,
    "CreatedAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);

ALTER TABLE public."Favorites" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Favorites_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public."OrderItems" (
    "Id" integer NOT NULL,
    "OrderId" integer NOT NULL,
    "ProductId" integer NOT NULL,
    "ProductVariantId" integer NOT NULL,
    "ProductName" character varying(180) NOT NULL,
    "VariantName" character varying(80) NOT NULL,
    "Sku" character varying(64) NOT NULL,
    "Size" integer NOT NULL,
    "Quantity" integer NOT NULL,
    "Price" numeric(10,2) NOT NULL,
    "ImageUrl" character varying(512) DEFAULT ''::character varying NOT NULL,
    CONSTRAINT "CK_OrderItems_Price" CHECK (("Price" > (0)::numeric)),
    CONSTRAINT "CK_OrderItems_Quantity" CHECK (("Quantity" > 0)),
    CONSTRAINT "CK_OrderItems_Size" CHECK ((("Size" >= 30) AND ("Size" <= 50)))
);

ALTER TABLE public."OrderItems" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."OrderItems_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public."Orders" (
    "Id" integer NOT NULL,
    "UserId" text,
    "CustomerName" character varying(80) NOT NULL,
    "Phone" character varying(32) NOT NULL,
    "DeliveryMethod" character varying(32) NOT NULL,
    "Status" character varying(24) NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "Total" numeric(10,2) NOT NULL,
    "Apartment" character varying(20),
    "City" character varying(80),
    "Comment" character varying(500),
    "Email" character varying(254),
    "House" character varying(20),
    "LastName" character varying(80),
    "PaymentMethod" character varying(24) DEFAULT 'cash'::character varying NOT NULL,
    "Postcode" character varying(12),
    "PublicId" uuid DEFAULT gen_random_uuid() NOT NULL,
    "Street" character varying(120),
    CONSTRAINT "CK_Orders_Total" CHECK (("Total" >= (0)::numeric))
);

ALTER TABLE public."Orders" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Orders_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public."ProductVariantImages" (
    "Id" integer NOT NULL,
    "ProductVariantId" integer NOT NULL,
    "ImageUrl" character varying(512) NOT NULL,
    "SortOrder" integer NOT NULL,
    "ThumbnailUrl" character varying(512)
);

ALTER TABLE public."ProductVariantImages" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."ProductVariantImages_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public."ProductVariantSizes" (
    "Id" integer NOT NULL,
    "ProductVariantId" integer NOT NULL,
    "Size" integer NOT NULL,
    "StockQuantity" integer NOT NULL,
    CONSTRAINT "CK_ProductVariantSizes_Size" CHECK ((("Size" >= 30) AND ("Size" <= 50))),
    CONSTRAINT "CK_ProductVariantSizes_Stock" CHECK ((("StockQuantity" >= 0) AND ("StockQuantity" <= 999)))
);

ALTER TABLE public."ProductVariantSizes" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."ProductVariantSizes_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public."ProductVariants" (
    "Id" integer NOT NULL,
    "ProductId" integer NOT NULL,
    "Name" public.citext NOT NULL,
    "Sku" public.citext NOT NULL,
    "Swatch" character varying(24) NOT NULL,
    "ImageUrl" character varying(512) NOT NULL,
    "IsDefault" boolean NOT NULL,
    "ThumbnailUrl" character varying(512)
);

ALTER TABLE public."ProductVariants" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."ProductVariants_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public."Products" (
    "Id" integer NOT NULL,
    "Name" character varying(100) NOT NULL,
    "Description" character varying(2000) NOT NULL,
    "Price" numeric(10,2) NOT NULL,
    "OldPrice" numeric(10,2),
    "ImageUrl" text,
    "IsNew" boolean NOT NULL,
    "IsPopular" boolean NOT NULL,
    "Status" character varying(16) NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    "BrandId" integer NOT NULL,
    "CategoryId" integer NOT NULL,
    CONSTRAINT "CK_Products_OldPrice" CHECK ((("OldPrice" IS NULL) OR ("OldPrice" > "Price"))),
    CONSTRAINT "CK_Products_Price_Positive" CHECK (("Price" > (0)::numeric))
);

ALTER TABLE public."Products" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Products_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public."Favorites"
    ADD CONSTRAINT "Favorites_pkey" PRIMARY KEY ("Id");

ALTER TABLE ONLY public."AspNetRoleClaims"
    ADD CONSTRAINT "PK_AspNetRoleClaims" PRIMARY KEY ("Id");

ALTER TABLE ONLY public."AspNetRoles"
    ADD CONSTRAINT "PK_AspNetRoles" PRIMARY KEY ("Id");

ALTER TABLE ONLY public."AspNetUserClaims"
    ADD CONSTRAINT "PK_AspNetUserClaims" PRIMARY KEY ("Id");

ALTER TABLE ONLY public."AspNetUserLogins"
    ADD CONSTRAINT "PK_AspNetUserLogins" PRIMARY KEY ("LoginProvider", "ProviderKey");

ALTER TABLE ONLY public."AspNetUserRoles"
    ADD CONSTRAINT "PK_AspNetUserRoles" PRIMARY KEY ("UserId", "RoleId");

ALTER TABLE ONLY public."AspNetUserTokens"
    ADD CONSTRAINT "PK_AspNetUserTokens" PRIMARY KEY ("UserId", "LoginProvider", "Name");

ALTER TABLE ONLY public."AspNetUsers"
    ADD CONSTRAINT "PK_AspNetUsers" PRIMARY KEY ("Id");

ALTER TABLE ONLY public."Brands"
    ADD CONSTRAINT "PK_Brands" PRIMARY KEY ("Id");

ALTER TABLE ONLY public."CatalogAuditLogs"
    ADD CONSTRAINT "PK_CatalogAuditLogs" PRIMARY KEY ("Id");

ALTER TABLE ONLY public."Categories"
    ADD CONSTRAINT "PK_Categories" PRIMARY KEY ("Id");

ALTER TABLE ONLY public."OrderItems"
    ADD CONSTRAINT "PK_OrderItems" PRIMARY KEY ("Id");

ALTER TABLE ONLY public."Orders"
    ADD CONSTRAINT "PK_Orders" PRIMARY KEY ("Id");

ALTER TABLE ONLY public."ProductVariantImages"
    ADD CONSTRAINT "PK_ProductVariantImages" PRIMARY KEY ("Id");

ALTER TABLE ONLY public."ProductVariantSizes"
    ADD CONSTRAINT "PK_ProductVariantSizes" PRIMARY KEY ("Id");

ALTER TABLE ONLY public."ProductVariants"
    ADD CONSTRAINT "PK_ProductVariants" PRIMARY KEY ("Id");

ALTER TABLE ONLY public."Products"
    ADD CONSTRAINT "PK_Products" PRIMARY KEY ("Id");

CREATE INDEX "EmailIndex" ON public."AspNetUsers" USING btree ("NormalizedEmail");

CREATE INDEX "IX_AspNetRoleClaims_RoleId" ON public."AspNetRoleClaims" USING btree ("RoleId");

CREATE INDEX "IX_AspNetUserClaims_UserId" ON public."AspNetUserClaims" USING btree ("UserId");

CREATE INDEX "IX_AspNetUserLogins_UserId" ON public."AspNetUserLogins" USING btree ("UserId");

CREATE INDEX "IX_AspNetUserRoles_RoleId" ON public."AspNetUserRoles" USING btree ("RoleId");

CREATE UNIQUE INDEX "IX_Brands_Name" ON public."Brands" USING btree ("Name");

CREATE INDEX "IX_Brands_Name_Trgm" ON public."Brands" USING gin ("Name" public.gin_trgm_ops);

CREATE INDEX "IX_CatalogAuditLogs_CreatedAt" ON public."CatalogAuditLogs" USING btree ("CreatedAt" DESC);

CREATE UNIQUE INDEX "IX_Categories_Name" ON public."Categories" USING btree ("Name");

CREATE UNIQUE INDEX "IX_Favorites_UserId_ProductId" ON public."Favorites" USING btree ("UserId", "ProductId");

CREATE INDEX "IX_OrderItems_OrderId" ON public."OrderItems" USING btree ("OrderId");

CREATE INDEX "IX_OrderItems_ProductVariantId" ON public."OrderItems" USING btree ("ProductVariantId");

CREATE UNIQUE INDEX "IX_Orders_PublicId" ON public."Orders" USING btree ("PublicId");

CREATE INDEX "IX_Orders_UserId_CreatedAt" ON public."Orders" USING btree ("UserId", "CreatedAt");

CREATE UNIQUE INDEX "IX_ProductVariantImages_ProductVariantId_SortOrder" ON public."ProductVariantImages" USING btree ("ProductVariantId", "SortOrder");

CREATE UNIQUE INDEX "IX_ProductVariantSizes_ProductVariantId_Size" ON public."ProductVariantSizes" USING btree ("ProductVariantId", "Size");

CREATE UNIQUE INDEX "IX_ProductVariants_ProductId_Name" ON public."ProductVariants" USING btree ("ProductId", "Name");

CREATE UNIQUE INDEX "IX_ProductVariants_Sku" ON public."ProductVariants" USING btree ("Sku");

CREATE INDEX "IX_ProductVariants_Sku_Trgm" ON public."ProductVariants" USING gin ("Sku" public.gin_trgm_ops);

CREATE INDEX "IX_Products_BrandId" ON public."Products" USING btree ("BrandId");

CREATE INDEX "IX_Products_CategoryId" ON public."Products" USING btree ("CategoryId");

CREATE INDEX "IX_Products_Name_Trgm" ON public."Products" USING gin ("Name" public.gin_trgm_ops);

CREATE INDEX "IX_Products_Status" ON public."Products" USING btree ("Status");

CREATE INDEX "IX_Products_Status_BrandId" ON public."Products" USING btree ("Status", "BrandId");

CREATE INDEX "IX_Products_Status_CategoryId" ON public."Products" USING btree ("Status", "CategoryId");

CREATE INDEX "IX_Products_Status_IsPopular_IsNew" ON public."Products" USING btree ("Status", "IsPopular", "IsNew");

CREATE UNIQUE INDEX "RoleNameIndex" ON public."AspNetRoles" USING btree ("NormalizedName");

CREATE UNIQUE INDEX "UserNameIndex" ON public."AspNetUsers" USING btree ("NormalizedUserName");

ALTER TABLE ONLY public."AspNetRoleClaims"
    ADD CONSTRAINT "FK_AspNetRoleClaims_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES public."AspNetRoles"("Id") ON DELETE CASCADE;

ALTER TABLE ONLY public."AspNetUserClaims"
    ADD CONSTRAINT "FK_AspNetUserClaims_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES public."AspNetUsers"("Id") ON DELETE CASCADE;

ALTER TABLE ONLY public."AspNetUserLogins"
    ADD CONSTRAINT "FK_AspNetUserLogins_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES public."AspNetUsers"("Id") ON DELETE CASCADE;

ALTER TABLE ONLY public."AspNetUserRoles"
    ADD CONSTRAINT "FK_AspNetUserRoles_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES public."AspNetRoles"("Id") ON DELETE CASCADE;

ALTER TABLE ONLY public."AspNetUserRoles"
    ADD CONSTRAINT "FK_AspNetUserRoles_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES public."AspNetUsers"("Id") ON DELETE CASCADE;

ALTER TABLE ONLY public."AspNetUserTokens"
    ADD CONSTRAINT "FK_AspNetUserTokens_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES public."AspNetUsers"("Id") ON DELETE CASCADE;

ALTER TABLE ONLY public."OrderItems"
    ADD CONSTRAINT "FK_OrderItems_Orders_OrderId" FOREIGN KEY ("OrderId") REFERENCES public."Orders"("Id") ON DELETE CASCADE;

ALTER TABLE ONLY public."OrderItems"
    ADD CONSTRAINT "FK_OrderItems_ProductVariants_ProductVariantId" FOREIGN KEY ("ProductVariantId") REFERENCES public."ProductVariants"("Id") ON DELETE RESTRICT;

ALTER TABLE ONLY public."Orders"
    ADD CONSTRAINT "FK_Orders_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES public."AspNetUsers"("Id") ON DELETE SET NULL;

ALTER TABLE ONLY public."ProductVariantImages"
    ADD CONSTRAINT "FK_ProductVariantImages_ProductVariants_ProductVariantId" FOREIGN KEY ("ProductVariantId") REFERENCES public."ProductVariants"("Id") ON DELETE CASCADE;

ALTER TABLE ONLY public."ProductVariantSizes"
    ADD CONSTRAINT "FK_ProductVariantSizes_ProductVariants_ProductVariantId" FOREIGN KEY ("ProductVariantId") REFERENCES public."ProductVariants"("Id") ON DELETE CASCADE;

ALTER TABLE ONLY public."ProductVariants"
    ADD CONSTRAINT "FK_ProductVariants_Products_ProductId" FOREIGN KEY ("ProductId") REFERENCES public."Products"("Id") ON DELETE CASCADE;

ALTER TABLE ONLY public."Products"
    ADD CONSTRAINT "FK_Products_Brands_BrandId" FOREIGN KEY ("BrandId") REFERENCES public."Brands"("Id") ON DELETE CASCADE;

ALTER TABLE ONLY public."Products"
    ADD CONSTRAINT "FK_Products_Categories_CategoryId" FOREIGN KEY ("CategoryId") REFERENCES public."Categories"("Id") ON DELETE CASCADE;

ALTER TABLE ONLY public."Favorites"
    ADD CONSTRAINT "Favorites_ProductId_fkey" FOREIGN KEY ("ProductId") REFERENCES public."Products"("Id") ON DELETE CASCADE;

COMMIT;
